selected_scheme scheme-full
TEXDIR /usr/local/texlive/2018
TEXMFCONFIG ~/.texlive2018/texmf-config
TEXMFHOME ~/texmf
TEXMFLOCAL /usr/local/texlive/texmf-local
TEXMFSYSCONFIG /usr/local/texlive/2018/texmf-config
TEXMFSYSVAR /usr/local/texlive/2018/texmf-var
TEXMFVAR ~/.texlive2018/texmf-var
binary_x86_64-linux 1
instopt_adjustpath 1
instopt_adjustrepo 0
