selected_scheme scheme-small
TEXDIR /usr/local/texlive/2019
TEXMFCONFIG ~/.texlive2019/texmf-config
TEXMFHOME ~/texmf
TEXMFLOCAL /usr/local/texlive/texmf-local
TEXMFSYSCONFIG /usr/local/texlive/2019/texmf-config
TEXMFSYSVAR /usr/local/texlive/2019/texmf-var
TEXMFVAR ~/.texlive2019/texmf-var
binary_x86_64-linuxmusl 1
instopt_adjustpath 1
instopt_adjustrepo 0
